name: Build & Deploy Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build code
      run: |
        # Voer hier de opdrachten uit om de code te bouwen

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          dist/
          node_modules/

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: 145.93.98.73
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        script: |
          # Voer hier de opdrachten uit om de code op de externe server te implementeren, bijv.:
          rm -rf $tmp_dir
          tmp_dir=$(mktemp -d)
          git clone https://github.com/11Poggie11/test.git $tmp_dir
          cp -R $tmp_dir/* /var/www/html/
          rm -rf $tmp_dir
