name: Pipeline Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          dist/
          node_modules/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH connection
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: C:\Users\Patrick\.ssh\opensshkey

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: /tmp/build

    - name: Copy files to Docker container
      run: |
        ssh -i C:\Users\Patrick\.ssh\opensshkey -o StrictHostKeyChecking=no root@localhost -p 2222 << EOF
          rm -rf /var/www/html/*
          mkdir -p /var/www/html/
          cp -R /tmp/build/* /var/www/html/
        EOF
